FROM golang:alpine as builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o client -v -ldflags="-w -s" ./client/

FROM busybox

WORKDIR /app

COPY --from=builder /app/client /usr/bin/

ENTRYPOINT ["client"]